export interface Movie {
  title: string;
  duration: string;
  producer: string;
  director: string;
  majorCast: string;
  rating: string;
  previewLocation: string;
  language: string;
  consumerAdvice: string;
  dateOfApproval: string;
  productionCompany: string;
  featured?: boolean;
  trailerUrl?: string;
  juryNote?: string;
}

export interface ApprovedMoviesPost {
  slug: string;
  title: string;
  date: string;
  publishedBy: string;
  image?: string;
  movies: Movie[];
}

export const approvedMoviesPosts: ApprovedMoviesPost[] = [
  {
    slug: "approved-movies-march-2026",
    title: "Approved Movies — March 2026",
    date: "2026-04-05",
    publishedBy: "ICT Unit",
    movies: [
      {
        title: "Ìgbà Àyé",
        duration: "1hr 52min",
        producer: "Tope Adebayo",
        director: "Kemi Adetiba",
        majorCast: "Bimbo Ademoye, Ramsey Nouah, Toyin Abraham",
        rating: "PG",
        previewLocation: "NFVCB Head Office, Abuja",
        language: "Yoruba",
        consumerAdvice: "Mild thematic elements; parental guidance advised",
        dateOfApproval: "2026-03-04",
        productionCompany: "Inkblot Productions",
      },
      {
        title: "Blood Meridian",
        duration: "2hr 10min",
        producer: "Charles Okwuosa",
        director: "Daniel Oriahi",
        majorCast: "Sani Muazu, Nse Ikpe-Etim, Chidi Mokeme",
        rating: "18",
        previewLocation: "NFVCB Head Office, Abuja",
        language: "English",
        consumerAdvice: "Strong violence, adult themes; not for children",
        dateOfApproval: "2026-03-05",
        productionCompany: "Zuma Film Productions",
      },
      {
        title: "Abubakar's Dream",
        duration: "1hr 38min",
        producer: "Maryam Usman",
        director: "Saddiq Balewa",
        majorCast: "Ali Nuhu, Rahama Sadau, Adam A. Zango",
        rating: "G",
        previewLocation: "NFVCB Kano Zonal Office",
        language: "Hausa",
        consumerAdvice: "Suitable for all audiences",
        dateOfApproval: "2026-03-06",
        productionCompany: "Kannywood Studios",
        featured: true,
        trailerUrl: "https://www.youtube.com/embed/dQw4w9WgXcQ",
        juryNote: "A triumphant family story rooted in northern Nigerian heritage. Outstanding storytelling, strong cultural values, and a G-rated experience that unites audiences of all ages.",
      },
      {
        title: "The Lagos Connection",
        duration: "1hr 45min",
        producer: "Joke Silva",
        director: "Niyi Akinmolayan",
        majorCast: "Joke Silva, Lateef Adedimeji, Osas Ighodaro",
        rating: "12",
        previewLocation: "NFVCB Head Office, Abuja",
        language: "English",
        consumerAdvice: "Moderate language; suitable for ages 12 and above",
        dateOfApproval: "2026-03-08",
        productionCompany: "Anthill Studios",
      },
      {
        title: "Nne",
        duration: "1hr 28min",
        producer: "Chioma Obi",
        director: "Stephanie Okereke-Linus",
        majorCast: "Genevieve Nnaji, Chioma Akpotha, Mercy Johnson",
        rating: "PG",
        previewLocation: "NFVCB Enugu Zonal Office",
        language: "Igbo",
        consumerAdvice: "Mild emotional content; parental guidance advised",
        dateOfApproval: "2026-03-10",
        productionCompany: "Obi Pictures",
      },
      {
        title: "Shattered Glass",
        duration: "1hr 55min",
        producer: "Emem Isong",
        director: "Amara Nwosu",
        majorCast: "Alexx Ekubo, Sharon Ooja, Timini Egbuson",
        rating: "15",
        previewLocation: "NFVCB Head Office, Abuja",
        language: "English",
        consumerAdvice: "Domestic violence themes; suitable for 15 and above",
        dateOfApproval: "2026-03-12",
        productionCompany: "Royal Arts Academy",
      },
      {
        title: "Adunola",
        duration: "1hr 35min",
        producer: "Biodun Stephen",
        director: "Biodun Stephen",
        majorCast: "Toyin Abraham, Lateef Adedimeji, Femi Adebayo",
        rating: "12A",
        previewLocation: "NFVCB Lagos Zonal Office",
        language: "Yoruba",
        consumerAdvice: "Mild scenes; children under 12 require adult accompaniment",
        dateOfApproval: "2026-03-13",
        productionCompany: "Sunstep Media",
      },
      {
        title: "Makama",
        duration: "2hr 05min",
        producer: "Hafsat Abdullahi",
        director: "Saddiq Balewa",
        majorCast: "Ali Nuhu, Hadiza Gabon, Bashir Ahmad",
        rating: "PG",
        previewLocation: "NFVCB Kano Zonal Office",
        language: "Hausa",
        consumerAdvice: "Suitable for family viewing with parental guidance",
        dateOfApproval: "2026-03-15",
        productionCompany: "Arewa Entertainment",
      },
      {
        title: "Echoes of Tomorrow",
        duration: "1hr 42min",
        producer: "Uche Jombo",
        director: "Mildred Okwo",
        majorCast: "Uche Jombo, Jim Iyke, Ini Edo",
        rating: "12",
        previewLocation: "NFVCB Head Office, Abuja",
        language: "English",
        consumerAdvice: "Moderate thematic content; ages 12 and above",
        dateOfApproval: "2026-03-17",
        productionCompany: "Team Capitalfish",
      },
      {
        title: "Ụzọ Ndụ",
        duration: "1hr 30min",
        producer: "Chukwuemeka Obi",
        director: "Frank Rajah",
        majorCast: "Patience Ozokwo, Ngozi Ezeonu, Pete Edochie",
        rating: "G",
        previewLocation: "NFVCB Enugu Zonal Office",
        language: "Igbo",
        consumerAdvice: "Suitable for all audiences",
        dateOfApproval: "2026-03-18",
        productionCompany: "GreatAsha Pictures",
      },
      {
        title: "Le Retour",
        duration: "1hr 48min",
        producer: "Jean-Pierre Okonkwo",
        director: "Victor Gaston",
        majorCast: "Nse Ikpe-Etim, Bisola Aiyeola, Deyemi Okanlawon",
        rating: "12A",
        previewLocation: "NFVCB Head Office, Abuja",
        language: "French",
        consumerAdvice: "Children under 12 need adult accompaniment",
        dateOfApproval: "2026-03-20",
        productionCompany: "Afrique Films",
      },
      {
        title: "Ìbòrí",
        duration: "1hr 22min",
        producer: "Femi Adebayo",
        director: "Adebayo Tijani",
        majorCast: "Femi Adebayo, Odunlade Adekola, Antar Laniyan",
        rating: "PG",
        previewLocation: "NFVCB Lagos Zonal Office",
        language: "Yoruba",
        consumerAdvice: "Mild traditional content; parental guidance advised",
        dateOfApproval: "2026-03-22",
        productionCompany: "Femi Adebayo Productions",
      },
    ],
  },
  {
    slug: "approved-movies-february-2026",
    title: "Approved Movies — February 2026",
    date: "2026-03-07",
    publishedBy: "ICT Unit",
    movies: [
      {
        title: "Ìfẹ́",
        duration: "1hr 40min",
        producer: "Mo Abudu",
        director: "Kemi Adetiba",
        majorCast: "Bimbo Ademoye, Stan Nze, Deyemi Okanlawon",
        rating: "12",
        previewLocation: "NFVCB Head Office, Abuja",
        language: "Yoruba",
        consumerAdvice: "Romantic themes; suitable for ages 12 and above",
        dateOfApproval: "2026-02-03",
        productionCompany: "EbonyLife Films",
      },
      {
        title: "Northern Winds",
        duration: "1hr 58min",
        producer: "Ibrahim Sheme",
        director: "Saddiq Balewa",
        majorCast: "Ali Nuhu, Adam A. Zango, Rahama Sadau",
        rating: "PG",
        previewLocation: "NFVCB Kano Zonal Office",
        language: "Hausa",
        consumerAdvice: "Suitable for family viewing; parental guidance advised",
        dateOfApproval: "2026-02-04",
        productionCompany: "Tambawal Films",
      },
      {
        title: "Obi of Lagos",
        duration: "2hr 02min",
        producer: "Nkiru Sylvanus",
        director: "Charles Okpaleke",
        majorCast: "Ramsey Nouah, Rita Dominic, Kanayo O. Kanayo",
        rating: "15",
        previewLocation: "NFVCB Head Office, Abuja",
        language: "English",
        consumerAdvice: "Strong thematic elements; 15 and above",
        dateOfApproval: "2026-02-06",
        productionCompany: "Play Network Studios",
      },
      {
        title: "Isi Ewu",
        duration: "1hr 33min",
        producer: "Emeka Mba",
        director: "Tchidi Chikere",
        majorCast: "Chioma Akpotha, Ngozi Ezeonu, Patience Ozokwo",
        rating: "G",
        previewLocation: "NFVCB Enugu Zonal Office",
        language: "Igbo",
        consumerAdvice: "Suitable for all audiences",
        dateOfApproval: "2026-02-08",
        productionCompany: "Chikere Films",
      },
      {
        title: "The Outsider",
        duration: "1hr 50min",
        producer: "Tope Oshin",
        director: "Tope Oshin",
        majorCast: "Toyin Abraham, Jide Kene Achufusi, Boma Akpore",
        rating: "12",
        previewLocation: "NFVCB Head Office, Abuja",
        language: "English",
        consumerAdvice: "Moderate content; ages 12 and above",
        dateOfApproval: "2026-02-10",
        productionCompany: "New Dawn Pictures",
      },
      {
        title: "Àánú",
        duration: "1hr 27min",
        producer: "Yemi Oduwole",
        director: "Adebayo Tijani",
        majorCast: "Odunlade Adekola, Mercy Aigbe, Femi Adebayo",
        rating: "PG",
        previewLocation: "NFVCB Lagos Zonal Office",
        language: "Yoruba",
        consumerAdvice: "Mild content; parental guidance advised",
        dateOfApproval: "2026-02-12",
        productionCompany: "Oluwole Productions",
      },
      {
        title: "Fractures",
        duration: "1hr 44min",
        producer: "Kayode Kasum",
        director: "Kayode Kasum",
        majorCast: "Lateef Adedimeji, Osas Ighodaro, Femi Jacobs",
        rating: "18",
        previewLocation: "NFVCB Head Office, Abuja",
        language: "English",
        consumerAdvice: "Adult themes and language; strictly for adults",
        dateOfApproval: "2026-02-14",
        productionCompany: "KKD Productions",
      },
      {
        title: "Nwoke Ọcha",
        duration: "1hr 36min",
        producer: "Charles Inojie",
        director: "Amaka Igwe",
        majorCast: "Charles Inojie, Chiwetalu Agu, Patience Ozokwo",
        rating: "G",
        previewLocation: "NFVCB Port Harcourt Zonal Office",
        language: "Igbo",
        consumerAdvice: "Suitable for all audiences",
        dateOfApproval: "2026-02-17",
        productionCompany: "Inojie Films",
      },
      {
        title: "Desert Rose",
        duration: "1hr 55min",
        producer: "Yakubu Mohammed",
        director: "Aminu Bello",
        majorCast: "Rabilu Musa, Hauwa Ali, Sani Danja",
        rating: "12A",
        previewLocation: "NFVCB Kano Zonal Office",
        language: "Hausa",
        consumerAdvice: "Children under 12 require adult accompaniment",
        dateOfApproval: "2026-02-19",
        productionCompany: "Desert Wind Films",
      },
    ],
  },
  {
    slug: "approved-movies-january-2026",
    title: "Approved Movies — January 2026",
    date: "2026-02-05",
    publishedBy: "ICT Unit",
    movies: [
      {
        title: "New Year, New Lies",
        duration: "1hr 38min",
        producer: "Uche Jombo",
        director: "Blessing Egbe",
        majorCast: "Uche Jombo, Enyinna Nwigwe, Angela Okorie",
        rating: "12",
        previewLocation: "NFVCB Head Office, Abuja",
        language: "English",
        consumerAdvice: "Moderate language and themes; ages 12 and above",
        dateOfApproval: "2026-01-07",
        productionCompany: "Uche Jombo Studios",
      },
      {
        title: "Ariwo Ko",
        duration: "1hr 45min",
        producer: "Femi Adebayo",
        director: "Niyi Akinmolayan",
        majorCast: "Femi Adebayo, Odunlade Adekola, Toyin Abraham",
        rating: "PG",
        previewLocation: "NFVCB Lagos Zonal Office",
        language: "Yoruba",
        consumerAdvice: "Suitable for family viewing with parental guidance",
        dateOfApproval: "2026-01-09",
        productionCompany: "Anthill Studios",
      },
      {
        title: "Eziagụ",
        duration: "1hr 30min",
        producer: "Amaka Igwe",
        director: "Tchidi Chikere",
        majorCast: "Patience Ozokwo, Pete Edochie, Genevieve Nnaji",
        rating: "G",
        previewLocation: "NFVCB Enugu Zonal Office",
        language: "Igbo",
        consumerAdvice: "Suitable for all audiences",
        dateOfApproval: "2026-01-10",
        productionCompany: "Peacocks Production",
      },
      {
        title: "Iron Walls",
        duration: "2hr 00min",
        producer: "Charles Okwuosa",
        director: "Izu Ojukwu",
        majorCast: "Sani Muazu, Chidi Mokeme, Hakeem Kae-Kazim",
        rating: "18",
        previewLocation: "NFVCB Head Office, Abuja",
        language: "English",
        consumerAdvice: "Graphic violence and adult content; strictly 18+",
        dateOfApproval: "2026-01-12",
        productionCompany: "Mainframe Films",
      },
      {
        title: "Labule",
        duration: "1hr 40min",
        producer: "Ahmed Nuhu",
        director: "Saddiq Balewa",
        majorCast: "Ali Nuhu, Rahama Sadau, Adam A. Zango",
        rating: "G",
        previewLocation: "NFVCB Kano Zonal Office",
        language: "Hausa",
        consumerAdvice: "Suitable for all audiences",
        dateOfApproval: "2026-01-14",
        productionCompany: "Nuhu Productions",
      },
      {
        title: "Obele",
        duration: "1hr 35min",
        producer: "Stephanie Okereke-Linus",
        director: "Stephanie Okereke-Linus",
        majorCast: "Nse Ikpe-Etim, Ozzy Agu, Shaffy Bello",
        rating: "15",
        previewLocation: "NFVCB Head Office, Abuja",
        language: "English",
        consumerAdvice: "Strong emotional and adult themes; 15 and above",
        dateOfApproval: "2026-01-16",
        productionCompany: "Linus Productions",
      },
      {
        title: "Ìdílé",
        duration: "1hr 28min",
        producer: "Biodun Stephen",
        director: "Biodun Stephen",
        majorCast: "Toyin Abraham, Sola Sobowale, Bimbo Oshin",
        rating: "PG",
        previewLocation: "NFVCB Lagos Zonal Office",
        language: "Yoruba",
        consumerAdvice: "Family drama; parental guidance advised",
        dateOfApproval: "2026-01-18",
        productionCompany: "Sunstep Media",
      },
      {
        title: "Nnọọ",
        duration: "1hr 22min",
        producer: "Obi Emelonye",
        director: "Obi Emelonye",
        majorCast: "Jim Iyke, Olu Jacobs, Ngozi Ezeonu",
        rating: "12A",
        previewLocation: "NFVCB Enugu Zonal Office",
        language: "Igbo",
        consumerAdvice: "Children under 12 need adult accompaniment",
        dateOfApproval: "2026-01-20",
        productionCompany: "Obi Emelonye Productions",
      },
      {
        title: "Before Midnight",
        duration: "1hr 52min",
        producer: "Mo Abudu",
        director: "Kemi Adetiba",
        majorCast: "Sharon Ooja, Timini Egbuson, Deyemi Okanlawon",
        rating: "12",
        previewLocation: "NFVCB Head Office, Abuja",
        language: "English",
        consumerAdvice: "Romantic and mild adult themes; ages 12 and above",
        dateOfApproval: "2026-01-22",
        productionCompany: "EbonyLife Films",
      },
      {
        title: "Arewa Zuciya",
        duration: "1hr 33min",
        producer: "Maryam Bello",
        director: "Aminu Saira",
        majorCast: "Hadiza Gabon, Bashir Ahmad, Zainab Indomie",
        rating: "G",
        previewLocation: "NFVCB Kano Zonal Office",
        language: "Hausa",
        consumerAdvice: "Suitable for all audiences",
        dateOfApproval: "2026-01-24",
        productionCompany: "Arewa Hearts",
      },
      {
        title: "Borrowed Time",
        duration: "1hr 48min",
        producer: "Emem Isong",
        director: "Mildred Okwo",
        majorCast: "Ramsey Nouah, Rita Dominic, Ini Edo",
        rating: "15",
        previewLocation: "NFVCB Head Office, Abuja",
        language: "English",
        consumerAdvice: "Crime and violence themes; 15 and above",
        dateOfApproval: "2026-01-27",
        productionCompany: "Royal Arts Academy",
      },
    ],
  },
];

export function getApprovedMoviesPost(slug: string): ApprovedMoviesPost | undefined {
  return approvedMoviesPosts.find((p) => p.slug === slug);
}
